name: Flyway Migration Error
description: Reporta errores en las migraciones de Flyway ejecutadas en GitHub Actions
title: "[SERVER] Flyway Migration Error - [MIGRATION_FILE]"
labels: ["flyway", "bug", "migration-error"]
assignees: 
  - "${{ github.actor }}"
body:
  - type: markdown
    attributes:
      value: "## Flyway Migration Error Report"
  - type: input
    id: migration_file
    attributes:
      label: Archivo de Migración
      description: Nombre del archivo que causó el error
  - type: textarea
    id: error_message
    attributes:
      label: Mensaje de Error
  - type: input
    id: event_trigger
    attributes:
      label: Evento Disparador
  - type: input
    id: commit_hash
    attributes:
      label: Hash del Commit
  - type: input
    id: timestamp
    attributes:
      label: Fecha y Hora (UTC)
  - type: input
    id: git_actor
    attributes:
      label: Usuario Ejecutor
  - type: textarea
    id: logs
    attributes:
      label: Logs de Error
  - type: textarea
    id: additional_info
    attributes:
      label: Información Adicional
