name: Flyway Migration Error
description: Reporte automatizado de fallos en migraciones de base de datos
title: "[SERVER] Flyway Migration Error - [MIGRATION_FILE]"
labels: ["flyway", "bug", "migration-error"]
assignees: 
  - "Edward-Arroyave"  # Administrador fijo
body:
  - type: markdown
    attributes:
      value: |
        ## Flyway Migration Error Report
        **Error detectado automáticamente en el pipeline de CI/CD**

  - type: textarea
    id: error_details
    attributes:
      label: Detalles Técnicos
      description: Información técnica del error
      render: markdown

  - type: textarea
    id: error_message
    attributes:
      label: Logs del Error
      description: Últimas líneas relevantes del log
      render: shell

  - type: textarea
    id: additional_info
    attributes:
      label: Contexto Adicional
      description: Metadatos y configuración del entorno
      render: markdown
