---
name: Flyway Error Report
about: Reporte automatizado de errores en migraciones de base de datos
title: "[FLYWAY] [${ENV}] ${ERROR_TYPE} - ${SCRIPT_NAME}"
labels: flyway-error, env:${ENV}
assignees: Edward-Arroyave

---

## Error Details

**Server:**  
${SERVER}

**Database:**  
${DATABASE}

**Failed Component:**  
${FAILED_COMPONENT}

**Error Type:**  
${ERROR_TYPE}

## Technical Information

**Commit:**  
${COMMIT_LINK}

**Workflow:**  
${WORKFLOW_LINK}

**Timestamp:**  
${TIMESTAMP}

## Error Logs

```log
${ERROR_LOGS}
