CREATE EXTERNAL TABLE [carehis].[TB_Patient_Ext]
(
[IdPatient] [int] NOT NULL,
[IdIdentificationType] [tinyint] NOT NULL,
[IdentificationNumber] [varchar] (20) NOT NULL,
[FirstName] [varchar] (60) NOT NULL,
[SecondName] [varchar] (60) NULL,
[FirstLastName] [varchar] (60) NOT NULL,
[SecondLastName] [varchar] (60) NULL,
[IdNationality] [int] NULL,
[BirthDate] [date] NOT NULL,
[IdBiologicalSex] [tinyint] NOT NULL,
[IdGenderIdentity] [tinyint] NULL,
[IdCountry] [int] NULL,
[IdResidenceCity] [int] NULL,
[IdResidenceArea] [tinyint] NULL,
[IdNeighborhood] [smallint] NULL,
[IdSocialStratum] [tinyint] NULL,
[Address] [varchar] (100) NULL,
[TelephoneNumber] [varchar] (15) NULL,
[TelephoneNumber2] [varchar] (15) NULL,
[Email] [varchar] (200) NULL,
[IdOccupation] [int] NULL,
[IdEthnicCommunity] [tinyint] NULL,
[IdEthnicity] [tinyint] NULL,
[IdDisabilityCategory] [int] NULL,
[IdCivilStatus] [tinyint] NULL,
[NumberOfChildren] [int] NULL,
[IdSchooling] [tinyint] NULL,
[Pregnancy] [bit] NULL,
[IdHealthProviderEntity] [int] NULL,
[IdOccupationalRiskManager] [int] NULL,
[IdPensionFundAdministator] [int] NULL,
[IdCompany] [int] NULL,
[IdSubCompany] [int] NULL,
[IdAffiliationType] [tinyint] NULL,
[IdAffiliationCategory] [tinyint] NULL,
[PhotoNameContainer] [varchar] (150) NULL,
[PatientWeb_Password] [varchar] (120) NULL,
[PatientWeb_SessionDate] [datetime] NULL,
[PatientWeb_EncryptedPatientDate] [datetime] NULL,
[PatientWeb_EncryptedPatient] [varchar] (500) NULL,
[AccessResultWeb] [bit] NULL,
[ResultWeb_Password] [varchar] (120) NULL,
[ResultWeb_SessionDate] [datetime] NULL,
[ResultWeb_EncryptedPatientDate] [datetime] NULL,
[ResultWeb_EncryptedPatient] [varchar] (500) NULL,
[AcceptDataProcessingPolicy] [bit] NULL,
[DataProcessingPolicy] [varchar] (150) NULL,
[DataProcessingPolicySignature] [varchar] (150) NULL,
[ExpirationDataProcessingPolicy] [date] NULL,
[IdPatientOdoo] [int] NULL,
[IdThirdPersonOdoo] [int] NULL,
[Active_HIS] [bit] NOT NULL,
[Active_LIS] [bit] NOT NULL,
[CreationDate] [datetime] NOT NULL,
[UpdateDate] [datetime] NULL,
[DataBaseSource] [int] NULL,
[IdUserAction] [int] NOT NULL
)
WITH
(
DATA_SOURCE = [HIS_DEMO],
SCHEMA_NAME = N'dbo',
OBJECT_NAME = N'TB_Patient'
)
GO
